(()=>{
const D=window.LITH_PUBLIC_RC,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORAGE='LITH_LIFE_ARCHIVE_V100_FINAL_JOURNEY';
const PREFS='LITH_LIFE_ARCHIVE_V100_FINAL_PREFS';
const defaultState={visitedScenes:[],completedQuests:[],readerMode:'public',journeyTrail:[],archiveKeys:0,lastScene:null,updatedAt:null};
let state=load(STORAGE,defaultState),prefs=load(PREFS,{sound:false,haptics:true}),activeScene=state.lastScene||'SCN-SWEET-001',activeQuest='QST-VERSION-001',questStep=0,audioCtx=null;
const sceneBy=Object.fromEntries(D.scenes.map(x=>[x.id,x])),questBy=Object.fromEntries(D.quests.map(x=>[x.id,x]));
function safeStorageGet(kind,key){try{return window[kind].getItem(key)}catch(e){return null}}function safeStorageSet(kind,key,val){try{window[kind].setItem(key,val);return true}catch(e){return false}}function safeStorageRemove(kind,key){try{window[kind].removeItem(key);return true}catch(e){return false}}function load(k,f){try{return {...f,...JSON.parse(safeStorageGet('localStorage',k)||'{}')}}catch(e){return {...f}}}
function save(){state.updatedAt=new Date().toISOString();safeStorageSet('localStorage',STORAGE,JSON.stringify(state));renderJourney()}
function savePrefs(){safeStorageSet('localStorage',PREFS,JSON.stringify(prefs));renderSettings()}
function tone(freq=560,dur=.045){if(!prefs.sound)return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.045,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch(e){}}
function haptic(ms=10){if(prefs.haptics&&navigator.vibrate)navigator.vibrate(ms)}
function feedback(){tone();haptic()}
function addTrail(type,id){state.journeyTrail.push({type,id,at:new Date().toISOString()});state.journeyTrail=state.journeyTrail.slice(-100);save()}
function nav(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});feedback()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.view)));
function renderSettings(){$$('[data-setting="sound"]').forEach(b=>{b.textContent=prefs.sound?'🔊':'🔇';b.classList.toggle('active',prefs.sound)});$$('[data-setting="haptics"]').forEach(b=>{b.textContent=prefs.haptics?'📳':'◌';b.classList.toggle('active',prefs.haptics)})}
$$('[data-setting]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.setting;prefs[k]=!prefs[k];savePrefs();feedback()}));
function unlocked(w){const r=D.releaseUnlockRules[w.id]?.predicate||'always';if(r==='always')return true;if(r==='visitedScenes >= 1')return state.visitedScenes.length>=1;if(r==='completedQuests >= 1')return state.completedQuests.length>=1;return true}
function renderJourney(){const endOk=state.visitedScenes.length>=3&&state.completedQuests.length>=2;$('#journeyBar').innerHTML=[['VISITED',state.visitedScenes.length],['QUESTS',state.completedQuests.length],['ARCHIVE KEYS',state.archiveKeys],['LIVING END',endOk?'OPEN':'LOCKED']].map(([l,n])=>`<div class="journeyStat"><b>${n}</b><span>${l}</span></div>`).join('');$('#saveStatus').textContent=state.updatedAt?`LOCAL SAVE · ${new Date(state.updatedAt).toLocaleString()}`:'LOCAL SAVE · NEW JOURNEY';renderWorlds();renderEnding()}
function renderWorlds(){$('#worldGrid').innerHTML=D.storyWorlds.map(w=>{const u=unlocked(w);return `<article class="card world ${u?'':'locked'}"><div class="icon">${w.icon}</div><div class="eyebrow">${w.chapterLabel}</div><h3>${w.name}</h3><p>${w.description}</p><div class="meta"><span class="tag ${u?'good':'wait'}">${u?'UNLOCKED':'JOURNEY-LOCKED'}</span><span class="tag">PUBLIC</span></div><small>${w.releaseUnlock.note}</small><br><br><button class="btn ${u?'primary':''}" data-world="${w.id}" ${u?'':'disabled'}>${u?'ENTER WORLD':'LOCKED'}</button></article>`}).join('');$$('[data-world]').forEach(b=>b.addEventListener('click',()=>{const w=D.storyWorlds.find(x=>x.id===b.dataset.world);if(!unlocked(w))return;transition(w,()=>{activeScene=w.sceneId;openScene(activeScene);nav('story')})}))}
function transition(w,cb){const t=$('#chapterTransition');$('#transitionIcon').textContent=w.icon;$('#transitionTitle').textContent=w.name;t.classList.add('show');feedback();setTimeout(()=>{cb();setTimeout(()=>t.classList.remove('show'),180)},matchMedia('(prefers-reduced-motion:reduce)').matches?50:620)}
function scenePanels(id){return D.panels.filter(p=>p.sceneId===id).sort((a,b)=>a.order-b.order)}
function openScene(id){activeScene=id;state.lastScene=id;if(!state.visitedScenes.includes(id)){state.visitedScenes.push(id);state.archiveKeys+=1}addTrail('scene',id);renderStory();renderWebtoon()}
function modePrefix(p){if(state.readerMode==='research')return `[${(p.claimIds||[]).join(', ')||'METHOD'}] `;if(state.readerMode==='young'&&p.truth==='memory')return 'ความทรงจำ: ';if(state.readerMode==='future'&&p.kind==='boundary')return 'Context note: ';return ''}
function renderStory(){const scenes=D.scenes;$('#storyMenu').innerHTML=scenes.map(s=>`<button class="storyChoice ${s.id===activeScene?'active':''}" data-scene="${s.id}"><b>${s.icon||'◇'} ${s.title}</b><br><small>${s.readiness}</small></button>`).join('');$$('[data-scene]').forEach(b=>b.addEventListener('click',()=>{openScene(b.dataset.scene);feedback()}));const s=sceneBy[activeScene]||scenes[0];if(!s)return;const ps=scenePanels(s.id);$('#storyPlayer').innerHTML=`<div class="card player"><div class="eyebrow">${s.id} · ${s.readiness}</div><h2>${s.title}</h2><p>${s.objective}</p><div class="callout"><b>EVIDENCE BOUNDARY</b><br>${s.boundary}</div><div class="panelList">${ps.map((p,i)=>`<div class="panel"><div class="panelNo">${i+1}</div><div><div class="eyebrow">${p.kind} · ${p.truth}</div><div>${modePrefix(p)}${p.text}</div>${state.readerMode==='research'?`<div>${(p.claimIds||[]).map(c=>`<span class="claimChip">${c}</span>`).join('')}</div>`:''}</div></div>`).join('')}</div></div>`}
function renderWebtoon(){const s=sceneBy[activeScene]||D.scenes[0],ps=scenePanels(s.id);$('#webtoonTitle').textContent=`${s.title} · ${state.readerMode.toUpperCase()}`;$('#webtoonStrip').innerHTML=ps.map((p,i)=>`<article class="webPanel"><div class="copy"><div class="eyebrow">PANEL ${String(i+1).padStart(2,'0')} · ${p.truth}</div><p>${modePrefix(p)}${p.text}</p>${state.readerMode==='research'?`<small>${(p.claimIds||[]).join(' · ')}</small>`:''}</div></article>`).join('')}
function renderQuests(){$('#questMenu').innerHTML=D.quests.map(q=>`<button class="questBtn ${state.completedQuests.includes(q.id)?'done':''}" data-q="${q.id}"><b>${q.icon} ${q.title}</b><br><small>${state.completedQuests.includes(q.id)?'✓ COMPLETE':q.type}</small></button>`).join('');$$('[data-q]').forEach(b=>b.addEventListener('click',()=>{activeQuest=b.dataset.q;questStep=0;renderQuestStage();feedback()}));renderQuestStage()}
function renderQuestStage(){const q=questBy[activeQuest]||D.quests[0];if(!q){$('#questStage').innerHTML='';return}const st=q.steps[questStep];if(!st){if(!state.completedQuests.includes(q.id)){state.completedQuests.push(q.id);state.archiveKeys+=2;addTrail('quest',q.id)}$('#questStage').innerHTML=`<div class="card questStage"><div class="icon">🗝️</div><h2>QUEST COMPLETE</h2><p>${q.integrityRule}</p><button class="btn primary" id="again">PLAY AGAIN</button></div>`;$('#again').addEventListener('click',()=>{questStep=0;renderQuestStage()});renderJourney();tone(780,.09);haptic(25);return}$('#questStage').innerHTML=`<div class="card questStage"><div class="eyebrow">${q.id} · ${questStep+1}/${q.steps.length}</div><h2>${q.icon} ${q.title}</h2><h3>${st.prompt}</h3>${st.choices.map((c,i)=>`<button class="choice" data-c="${i}">${c.text}</button>`).join('')}<div id="feedback" class="record" aria-live="polite">เลือกคำตอบที่ไม่ก้าวเกินหลักฐาน</div></div>`;$$('[data-c]').forEach(b=>b.addEventListener('click',()=>{const c=st.choices[+b.dataset.c];b.classList.add(c.correct?'good':'bad');$$('[data-c]').forEach(x=>x.disabled=true);$('#feedback').innerHTML=`<b>${c.correct?'✓ PASS':'✕ EVIDENCE BOUNDARY'}</b><br>${c.why}`;c.correct?tone(700,.07):tone(210,.1);haptic(c.correct?12:28);setTimeout(()=>{questStep++;renderQuestStage()},900)}))}
function archiveRows(){const type=$('#archiveType').value,q=$('#archiveSearch').value.trim().toLowerCase(),map={source:D.sources,claim:D.claims,event:D.events,person:D.people,place:D.places,artifact:D.artifacts,media:D.mediaRecords};return (map[type]||[]).filter(x=>{const t=(x.title||x.name||x.id).toLowerCase();return !q||t.includes(q)||x.id.toLowerCase().includes(q)}).slice(0,60)}
function renderArchive(){$('#records').innerHTML=archiveRows().map(x=>`<div class="record"><div class="eyebrow">${x.id}</div><b>${x.title||x.name||x.id}</b><div class="meta"><span class="tag">${x.truth||x.status||'record'}</span><span class="tag">PUBLIC</span></div></div>`).join('')||'<div class="record">No matching public record.</div>'}
$('#archiveType').addEventListener('change',renderArchive);$('#archiveSearch').addEventListener('input',renderArchive);
function renderTime(){$('#timeRiver').innerHTML=D.timeAnchors.map(a=>`<button class="timeAnchor" data-time="${a.id}"><div class="eyebrow">${a.timeClass}</div><b>${a.label}</b><p>${a.display}</p></button>`).join('');$$('[data-time]').forEach(b=>b.addEventListener('click',()=>{const a=D.timeAnchors.find(x=>x.id===b.dataset.time);$('#timeDetail').innerHTML=`<div class="card"><h3>${a.label}</h3><p>${D.navigationPolicies.timeTravelLock}</p>${a.eventIds.map(id=>{const e=D.events.find(x=>x.id===id);return e?`<div class="record"><b>${e.title}</b><br><small>${e.id}</small></div>`:''}).join('')}</div>`;addTrail('time',a.id);feedback()}))}
function renderConstellation(){$('#stars').innerHTML=D.constellationNodes.map(n=>`<button class="star" style="left:${n.x}%;top:${n.y}%" data-star="${n.id}">${n.label}</button>`).join('');$$('[data-star]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.star,n=D.constellationNodes.find(x=>x.id===id),edges=D.constellationEdges.filter(e=>e.from===id||e.to===id);$('#starDetail').innerHTML=`<div class="card"><div class="eyebrow">${n.type} · DISPLAY-ONLY COORDINATES</div><h3>${n.label}</h3><p>${D.navigationPolicies.constellationLock}</p><div>${edges.slice(0,15).map(e=>`<span class="claimChip">${e.relation}: ${e.from===id?e.to:e.from}</span>`).join('')}</div></div>`;addTrail('constellation',id);feedback()}))}
function renderGate(){const g=D.releaseGate;$('#releaseGate').innerHTML=`<div class="gateItem"><b>${g.included.scenes}</b><span>PUBLIC SCENES</span></div><div class="gateItem"><b>${Object.values(g.withheldCounts).reduce((a,b)=>a+b,0)}</b><span>WITHHELD RECORD SLOTS</span></div><div class="gateItem"><b>0</b><span>PRIVATE / SEALED BUNDLED</span></div>`;$('#gateNote').textContent=g.withheldReason}
function renderEnding(){const ok=state.visitedScenes.length>=3&&state.completedQuests.length>=2;$('#ending').classList.toggle('locked',!ok);$('#ending').innerHTML=`<div class="endingInner"><div class="eyebrow">${ok?'LIVING ENDING UNLOCKED':'LIVING ENDING LOCKED'}</div><h2>${ok?'THE LIFE CONTINUES':'KEEP EXPLORING'}</h2><p>${ok?D.livingEnding.text:'เยี่ยมชมทั้ง 3 public scenes และทำอย่างน้อย 2 quests เพื่อเปิด milestone นี้ การปลดล็อกไม่มีผลต่อ canonical history'}</p>${ok?'<div class="icon">✦ ∞ ✦</div>':''}</div>`}
function exportJourney(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='LITH_LIFE_ARCHIVE_v1.0_FINAL_JOURNEY.json';a.click();URL.revokeObjectURL(a.href)}
$('#exportJourney').addEventListener('click',exportJourney);$('#resetJourney').addEventListener('click',()=>{if(confirm('Reset local reader journey? Canonical public archive data will not be changed.')){state={...defaultState};safeStorageRemove('localStorage',STORAGE);activeScene='SCN-SWEET-001';renderAll()}});
$('#readerMode').value=state.readerMode;$('#readerMode').addEventListener('change',e=>{state.readerMode=e.target.value;save();renderStory();renderWebtoon();feedback()});
function runtimeChecks(){const checks=[];checks.push(['Public corpus only',[...D.sources,...D.claims,...D.events,...D.people,...D.places,...D.artifacts,...D.mediaRecords,...D.scenes,...D.quests,...D.storyWorlds].every(x=>(x.privacy||'public')==='public')]);const sids=new Set(D.scenes.map(x=>x.id)),cids=new Set(D.claims.map(x=>x.id));checks.push(['Scene references',D.storyWorlds.every(w=>sids.has(w.sceneId))]);checks.push(['Panel claim references',D.panels.every(p=>sids.has(p.sceneId)&&(p.claimIds||[]).every(c=>cids.has(c)))]);checks.push(['Alternate history branches',D.releasePolicy.alternateHistoryBranches===0]);return checks}
function runLoader(){const checks=runtimeChecks(),box=$('#loaderChecks');box.innerHTML=checks.map(([l,ok])=>`<div class="check"><span>${l}</span><b class="${ok?'ok':''}">${ok?'PASS':'FAIL'}</b></div>`).join('');const pass=checks.every(x=>x[1]);setTimeout(()=>{if(pass){$('#loader').classList.add('done');startCinema()}else{$('#loaderTitle').textContent='PUBLIC BUILD CHECK FAILED'}},matchMedia('(prefers-reduced-motion:reduce)').matches?80:520)}
function startCinema(){const seen=safeStorageGet('sessionStorage','LITH_V100_CINEMA_SEEN');if(seen){$('#cinema').classList.add('hidden');return}const lines=$$('.cinemaLine');let i=0;const tick=()=>{lines.forEach((x,j)=>x.classList.toggle('on',j===i));i++;if(i<lines.length)setTimeout(tick,620)};tick()}
$('#enterArchive').addEventListener('click',()=>{safeStorageSet('sessionStorage','LITH_V100_CINEMA_SEEN','1');$('#cinema').classList.add('hidden');tone(660,.08);haptic(18)});$('#skipCinema').addEventListener('click',()=>{$('#cinema').classList.add('hidden');safeStorageSet('sessionStorage','LITH_V100_CINEMA_SEEN','1')});
function renderAll(){renderSettings();renderJourney();renderStory();renderWebtoon();renderQuests();renderArchive();renderTime();renderConstellation();renderGate();renderEnding()}
renderAll();runLoader();
})();